import { pgTable, serial, text, numeric, varchar, real, timestamp } from "drizzle-orm/pg-core";

// export const stones = pgTable("stones", {
//   id: serial("id").primaryKey(),
//   stoneId: text("stone_id").notNull().unique(),
//   clarity: text("clarity"),
//   measurements1: text("measurements"),
//   measurements2: text("measurements"),
//   measurements3:text("measurements"),
//   certificateNumber: text("certificate_number"),
//   shape: text("shape"),
//   lab: text("lab"),
//   carat: numeric("carat", { precision: 5, scale: 2 }).notNull(),
//   origin: text("origin"),
//   ratio: numeric("ratio", { precision: 4, scale: 2 }),
//   pricePerCarat: numeric("price_per_carat", { precision: 10, scale: 2 }),
//   totalPrice: numeric("total_price", { precision: 10, scale: 2 }),
//   certImage: text("cert_image"),
//   video: text("video"),
//   certPdf: text("cert_pdf"),
// });

// export const soapStones = pgTable('soap_stones', {
//   id: serial('id').primaryKey(),
//   sku: varchar('sku', { length: 64 }).notNull(),
//   shape: varchar('shape', { length: 64 }),
//   weight: real('weight'),
//   color: varchar('color', { length: 16 }),
//   clarity: varchar('clarity', { length: 16 }),
//   lab: varchar('lab', { length: 32 }),
//   fluorescence: varchar('fluorescence', { length: 32 }),
//   pricePerCarat: real('price_per_carat'),
//   totalPrice: real('total_price'),
//   image: text('image'),
//   video: text('video'),
//   certificateImage: text('certificate_image'),
//   polish: varchar('polish', { length: 16 }),
//   symmetry: varchar('symmetry', { length: 16 }),
//   tablePercent: real('table'),
//   depth: real('depth'),
//   ratio: real('ratio'),
//   measurements: varchar('measurements', { length: 128 }),
//   comment: text('comment'),
//   createdAt: timestamp('created_at').defaultNow(),
// });

export const jewelryProducts = pgTable('jewelry_products', {
  modelNumber: varchar('model_number', { length: 50 }).notNull().primaryKey(),
  stockNumber: varchar('stock_number', { length: 50 }),
  jewelryType: varchar('jewelry_type', { length: 50 }),
  style: varchar('style', { length: 50 }),
  collection: varchar('collection', { length: 100 }),
  price: numeric('price', { precision: 10, scale: 2 }),
  videoLink: text('video_link'),
  allPicturesLink: text('all_pictures_link'),
  certificateLink: text('certificate_link'),
  certificateNumber: varchar('certificate_number', { length: 100 }),
  title: varchar('title', { length: 150 }),
  description: text('description'),
  jewelryWeight: numeric('jewelry_weight', { precision: 10, scale: 2 }),
  totalCarat: numeric('total_carat', { precision: 10, scale: 2 }),
  stoneType: varchar('stone_type', { length: 50 }),
  centerStoneCarat: numeric('center_stone_carat', { precision: 10, scale: 2 }),
  centerStoneShape: varchar('center_stone_shape', { length: 50 }),
  centerStoneColor: varchar('center_stone_color', { length: 50 }),
  centerStoneClarity: varchar('center_stone_clarity', { length: 50 }),
  metalType: varchar('metal_type', { length: 50 }),
  currency: varchar('currency', { length: 10 }),
  availability: varchar('availability', { length: 50 }),
  shippingFrom: varchar('shipping_from', { length: 100 }),
  category: varchar('category', { length: 100 }),
  fullDescription: text('full_description'),
  jewelrySize: varchar('jewelry_size', { length: 50 }),
  instructionsMain: text('instructions_main'),
});