CREATE TABLE "soap_stones" (
	"id" serial PRIMARY KEY NOT NULL,
	"category" text,
	"sku" text NOT NULL,
	"shape" text,
	"weight" numeric,
	"color" text,
	"clarity" text,
	"lab" text,
	"fluorescence" text,
	"price_per_carat" numeric,
	"rap_price" numeric,
	"rap_list_price" numeric,
	"total_price" numeric,
	"location" text,
	"branch" text,
	"image" text,
	"additional_pictures" text,
	"video" text,
	"additional_videos" text,
	"certificate_image" text,
	"certificate_number" text,
	"certificate_image_jpg" text,
	"cut" text,
	"polish" text,
	"symmetry" text,
	"table_percent" numeric,
	"depth_percent" numeric,
	"ratio" numeric,
	"measurements" text,
	"fancy_intensity" text,
	"fancy_color" text,
	"fancy_overtone" text,
	"fancy_color_2" text,
	"fancy_overtone_2" text,
	"pair_stone" text,
	"home_page" text,
	"trade_show" text,
	"comment" text,
	"type" text,
	"cert_comments" text,
	"origin" text,
	"raw_xml" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "soap_stones_sku_unique" UNIQUE("sku")
);
